const URI_GATEWAY = "http://192.168.3.192:8080";
const PREFIX_MERCHANTS_SVC = "/merchants";
const STRIPE_API_URL = "http://192.168.3.192:4242"
const PREFIX_PAYMENT_INTENT = "/create-payment-intent";
const PREFIX_KRISMEMBERSHIP_SVC = "/krismembership";
const PREFIX_MERCHANTMEMBERSHIP_SVC = "/merchantmembership";

export const URL_MERCHANTS_SVC = URI_GATEWAY + PREFIX_MERCHANTS_SVC;
export const URL_KRISMEMBERSHIP = URI_GATEWAY + PREFIX_KRISMEMBERSHIP_SVC;
export const URL_MERCHANTMEMBERSHIP = URI_GATEWAY + PREFIX_MERCHANTMEMBERSHIP_SVC;
export const URL_PAYMENT_SVC = STRIPE_API_URL  + PREFIX_PAYMENT_INTENT;
