const URI_MERCHANT_SVC = " https://sq-app-challenge-16ca82b09b16.herokuapp.com";
const PREFIX_MERCHANTS = "/merchants";
const URI_STRIPE = "http://192.168.43.184:4242"
const PREFIX_PAYMENT_INTENT = "/create-payment-intent";
const PREFIX_KRISMEMBERSHIP = "/krismembership";
const PREFIX_MERCHANTMEMBERSHIP = "/merchantmembership";

export const URL_MERCHANTS_SVC = URI_MERCHANT_SVC + PREFIX_MERCHANTS;
export const URL_KRISMEMBERSHIP = URI_MERCHANT_SVC + PREFIX_KRISMEMBERSHIP;
export const URL_MERCHANTMEMBERSHIP = URI_MERCHANT_SVC + PREFIX_MERCHANTMEMBERSHIP;
export const URL_PAYMENT_SVC = URI_STRIPE  + PREFIX_PAYMENT_INTENT;
